app = "n8n-fly-thang"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  N8N_HOST = "n8n-fly-thang.fly.dev"
  WEBHOOK_URL = "https://n8n-fly-thang.fly.dev"
  N8N_BASIC_AUTH_ACTIVE = "true"
  N8N_BASIC_AUTH_USER = "admin"
  N8N_BASIC_AUTH_PASSWORD = "123456"

[http_service]
  internal_port = 5678
  force_https = true
  auto_start_machines = true
  min_machines_running = 1

[mounts]
  source = "n8n_data"
  destination = "/home/node/.n8n"
